@startmindmap Mindmap Media Lifecycle Management 
* Media Lifecycle Management
** Medienarten 
*** Spiele 
**** AR 
**** VR 
*** Audio 
**** Sprache 
**** Musik 
**** Hörbücher 
**** Podcast 
**** Radio  
**** CD 
**** Kassette
*** Video
**** Film 
**** Fernsehen  
*** Text
**** Sprache 
**** Printmedien 
***** Bücher 
***** Zeitschriften  
**** Theater 
*** Bild 

@endmindmap*** Audio 
*** Video 
*** Text 
*** Bild 
