@startmindmap Mindmap Media Lifecycle Management 
' root
+ Media Lifecycle Management
' left side 
-- Lehrveranstaltung
--- Lernportfolio 
--- Constructive Allignment 
' right side 
++ Medienarten 
+++ Spiele 
++++ AR 
++++ VR 
+++ Audio 
++++ Sprache 
++++ Musik 
++++ Hörbücher 
++++ Podcast 
++++ Radio  
++++ CD 
++++ Kassette
+++ Video
++++ Film 
++++ Fernsehen  
+++ Text
++++ Sprache 
++++ Printmedien 
+++++ Bücher 
+++++ Zeitschriften  
++++ Theater 
+++ Bild 

@endmindmap+++ Audio 
+++ Video 
+++ Text 
+++ Bild 
